### ISSUE TITLE
RTA並に頑張ってもランクがC

### ISSUE THREAD

**Issue by ayieru** [ayieru/Unity_GameAward#161]
悲しい。

**Comment by ayieru** [comment]
![image](https://user-images.githubusercontent.com/79795916/170897125-bca9b2c2-d17f-4c50-a15d-d3afd4cd897d.png)

**Comment by ayieru** [comment]
![image](https://user-images.githubusercontent.com/79795916/170897489-c217c354-6e79-4965-a38a-e7c7ab4fb96a.png)

**Comment by wonkle07** [comment]
Prefab>Goalのインスペクターで、
各ランクに対応したタイムを設定出来ます…
