### ISSUE TITLE
ギミックで動いている磁石にプレイヤーが触れると、磁石が止まってしまう

### ISSUE THREAD

**Issue by ArAkAwAyUU** [ayieru/Unity_GameAward#247]

**Comment by ArAkAwAyUU** [comment]
https://user-images.githubusercontent.com/72130649/177262052-e762dea9-a5ac-4c0f-81bb-b5ab84a2e5f6.mp4

**Comment by ayieru** [comment]
Rigitbodyが原因だと思う。
Magnetとプレイヤー両方にりじぼを付けると、りじぼが付いてるプレイヤーのポジションに強い力で引かれて止まるっていう流れだと思う。
transformでやるのがいいかも

https://github.com/ayieru/Unity_GameAward/blob/98970f779706e6f3bbcd84d27f8cd49a851ad13b/Magnet_Prot/Assets/Script/GimmickMoving.cs#L43-L44
