### ISSUE TITLE
ジャンプ修正

### ISSUE THREAD

**Issue by ayieru** [ayieru/Unity_GameAward#74]
どういった現象で起きるかはわからないけど、ジャンプキー押しても反応する時と反応しない時がある 
AT14B184_01_荒川湧 — 今日 18:16
@プログラマー ↑のバグ、じゃきおが修正終わった後で良いので、誰かこの修正やりますか？やらなければ俺が修正してみようかなと思うんだけど

**Comment by ArAkAwAyUU** [comment]
プルリク中
